### ISSUE TITLE
Flake support

### ISSUE THREAD

**Issue by considerate** [considerate/nixos-odroidhc4#7]
Most of this repo now boils down to providing an overlay, two nixos modules and a derivation to build the SD image. I think the machinery around that could benefit from the nix flake infrastructure.

This would mean that we don't need to pin the nixpkgs in such an ad-hoc way. It would also enable users to more easily customize their own system configurations.

**Comment by Patagonicus** [comment]
I've been looking into this for a bit and there's one problem: [Flakes don't support cross compilation (yet)](https://github.com/NixOS/nix/issues/5157).

I think we might be able to do something were most things are in the flake and then we have some non-flake wrapper using that for building the sd-image since that's the only thing that really needs cross compilation. I don't have much experience with making flakes work with non-flake systems, but there are adapter libraries.

**Comment by considerate** [comment]
@Patagonicus I think this should only really be an issue in the case of IFD (import from derivation) and since that's not used in this repo I think specifying `system == targetSystem` should be OK for this repo.

**Comment by considerate** [comment]
Closed by #14
